



import java.awt.Color;
import java.sql.*;
import javax.swing.*;
import javax.swing.text.Position;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SK
 */
public class DBMS1 extends javax.swing.JFrame {
     final void FillList()
    {
    try{
        String url="jdbc:h2:~/scc";
        
     Connection con = DriverManager.getConnection(url,"scc","scc"); 
     Statement stmt=con.createStatement();
     String Query="SELECT * FROM STUDENT ORDER BY ADNO";
     ResultSet rs=stmt.executeQuery(Query);
     DefaultListModel DLM= new DefaultListModel();
     while(rs.next())
     {
     DLM.addElement(rs.getString(1));
     }
     l1.setModel(DLM);
    }
    catch(SQLException ex) 
       {
       JOptionPane.showMessageDialog(null, ex.toString());
       }
    }


    /**
     * Creates new form DBMS1
     */
    public DBMS1() {
        initComponents(); setLocationRelativeTo(null);FillList();
        getContentPane().setBackground(new Color(255,210,150));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        l1 = new javax.swing.JList();
        jLabel6 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        mob = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        adno = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        sch = new javax.swing.JTextField();
        add = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        clas = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        sec = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        dob = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        july = new javax.swing.JTextField();
        april = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        may = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        june = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        tp = new javax.swing.JTextField();
        cbox1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1320, 720));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setBackground(new java.awt.Color(255, 0, 51));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("DELETE Record(s)");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 450, -1, 78));

        jButton5.setBackground(new java.awt.Color(0, 204, 51));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("UPDATE   DataBase");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 450, -1, 78));

        jButton3.setFont(new java.awt.Font("Microsoft JhengHei", 1, 16)); // NOI18N
        jButton3.setText("Clear All Fields");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 160, 151, 36));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 0, 204));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("#Fee Status (*Un-editable)");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 414, -1, -1));

        l1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Admission No.", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft JhengHei", 0, 14))); // NOI18N
        l1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l1.setToolTipText("");
        l1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        l1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                l1ValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(l1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 270, 241, 347));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("#Click on Admission No. to View Details.");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 240, -1, -1));

        jLabel30.setFont(new java.awt.Font("Microsoft JhengHei", 0, 15)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("DataBase : STUDENT");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 220, 241, -1));

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DataBase");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 797, 50));

        jLabel31.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 0, 0));
        jLabel31.setText("*Please note that Admission No. , DOB and Fee Status are non-editable fields.*");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("( View , Edit , Update and Delete data using DataBase Manager )");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 56, 797, -1));

        jLabel7.setBackground(new java.awt.Color(204, 255, 204));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("# Enter Admission No. :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 60, -1, -1));

        t1.setBackground(new java.awt.Color(204, 255, 204));
        t1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 90, 302, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SEARCH   DataBase");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 120, -1, 36));

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei", 2, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("**Designed By, Saurav Kumar");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 660, 216, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 135, 15));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home.jpg"))); // NOI18N
        jButton2.setText("     Return to HOME");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 620, -1, 59));

        mob.setBackground(new java.awt.Color(255, 255, 204));
        mob.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        getContentPane().add(mob, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 507, -1));

        jLabel10.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Father's Name");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 131, -1));

        jLabel11.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("School Name");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel26.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        jLabel26.setText("+91");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, -1, -1));

        jLabel27.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        jLabel27.setText(" : ");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, -1));

        jLabel28.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        jLabel28.setText(" : ");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));

        jLabel32.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        jLabel32.setText(" : ");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));

        adno.setEditable(false);
        adno.setBackground(new java.awt.Color(255, 255, 204));
        adno.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        getContentPane().add(adno, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 537, -1));

        jLabel14.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Address");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 138, -1));

        fname.setBackground(new java.awt.Color(255, 255, 204));
        fname.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        getContentPane().add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 537, -1));

        sch.setBackground(new java.awt.Color(255, 255, 204));
        sch.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        getContentPane().add(sch, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 537, -1));

        add.setBackground(new java.awt.Color(255, 255, 204));
        add.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 537, -1));

        name.setBackground(new java.awt.Color(255, 255, 204));
        name.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 537, -1));

        clas.setBackground(new java.awt.Color(255, 255, 204));
        clas.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        clas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clasActionPerformed(evt);
            }
        });
        getContentPane().add(clas, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 250, 420, -1));

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Admission No.*");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 131, -1));

        jLabel15.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Mobile No. ");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 138, -1));

        jLabel16.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        jLabel16.setText(" : ");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, -1));

        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Name");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 131, -1));

        jLabel17.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        jLabel17.setText(" : ");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, -1));

        jLabel19.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        jLabel19.setText(" : ");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, -1, -1));

        jLabel20.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        jLabel20.setText(" : ");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, -1));

        jLabel12.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Class");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 138, -1));

        jLabel24.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel24.setText("(8-digits)");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 100, 115, -1));

        jLabel21.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("(50-characters)");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 160, 115, -1));

        jLabel22.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("(50-characters)");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 190, 115, -1));

        jLabel25.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel25.setText("(100-characters)");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 280, 115, -1));

        jLabel46.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        jLabel46.setText(" : ");
        getContentPane().add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, -1));

        sec.setBackground(new java.awt.Color(255, 255, 204));
        sec.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        getContentPane().add(sec, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 537, -1));

        jLabel47.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel47.setText("Batch");
        getContentPane().add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 131, -1));

        dob.setEditable(false);
        dob.setBackground(new java.awt.Color(255, 255, 204));
        dob.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        getContentPane().add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 340, 537, -1));

        jLabel23.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel23.setText("YYYY-MM-DD");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(751, 343, 115, -1));

        jLabel8.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Date Of Birth (DOB)");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 343, -1, -1));

        jLabel33.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        jLabel33.setText(" : ");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, -1, -1));

        july.setEditable(false);
        july.setBackground(new java.awt.Color(255, 255, 204));
        july.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(july, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 530, 120, -1));

        april.setEditable(false);
        april.setBackground(new java.awt.Color(255, 255, 204));
        april.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(april, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 120, -1));

        jLabel34.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel34.setText("2nd Installment :");
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, -1, -1));

        may.setEditable(false);
        may.setBackground(new java.awt.Color(255, 255, 204));
        may.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        may.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mayActionPerformed(evt);
            }
        });
        getContentPane().add(may, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 120, -1));

        jLabel35.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel35.setText("3rd Installment :");
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, -1, -1));

        june.setEditable(false);
        june.setBackground(new java.awt.Color(255, 255, 204));
        june.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(june, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 500, 120, -1));

        jLabel36.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel36.setText("4th Installment :");
        getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, -1, -1));

        jLabel37.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel37.setText("1st Installment  :");
        getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        jLabel38.setFont(new java.awt.Font("Microsoft JhengHei", 0, 16)); // NOI18N
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel38.setText("*Total Fees Paid (Rs.) :");
        getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, -1, -1));

        tp.setEditable(false);
        tp.setBackground(new java.awt.Color(204, 255, 204));
        tp.setFont(new java.awt.Font("Microsoft JhengHei", 0, 15)); // NOI18N
        tp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(tp, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 480, 180, -1));

        cbox1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        cbox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Change Class", "11th", "12th" }));
        cbox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox1ActionPerformed(evt);
            }
        });
        getContentPane().add(cbox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 112, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        if(l1.getSelectedValue()!=(null)){

            try{
                String url="jdbc:h2:~/scc";

                Connection con = DriverManager.getConnection(url,"scc","scc");
                Statement stmt=con.createStatement();
                String Query="UPDATE STUDENT SET name='"+name.getText()+"',fname='"+fname.getText()+"',dob='"+dob.getText()+"', CLAS='"+clas.getText()+"',sec='"+sec.getText()+"',add='"+add.getText()+"',mob='"+mob.getText()+"',sch='"+sch.getText()+"' WHERE adno='"+l1.getSelectedValue()+"'";
                stmt.execute(Query);
                JOptionPane.showMessageDialog(null,"DataBase Updated Successfully.");

            }
            catch(SQLException ex)
            {
                JOptionPane.showMessageDialog(null, ex.toString());
            }
            
        }   else {
            JOptionPane.showMessageDialog(null, "No Record(s) Selected.");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
cbox1.setSelectedItem("Change Class");

        t1.setText(null);
        adno.setText(null);
        name.setText(null);
        fname.setText(null);
        dob.setText(null);
        clas.setText(null);
        sec.setText(null);
        add.setText(null);
        mob.setText(null);april.setText(null);
        may.setText(null);
        june.setText(null);
        july.setText(null);
        sch.setText(null);
        tp.setText(null);
          FillList();
        

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void l1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_l1ValueChanged

        try{
            String url="jdbc:h2:~/scc";

            Connection con = DriverManager.getConnection(url,"scc","scc");
            Statement stmt=con.createStatement();
            String Query="SELECT * FROM STUDENT where adno = '"+l1.getSelectedValue()+"'";
            ResultSet rs=stmt.executeQuery(Query);

            while(rs.next())
            {
                adno.setText(rs.getString(1));
                name.setText(rs.getString(2));
                fname.setText(rs.getString(3));
                dob.setText(rs.getString(4));
                clas.setText(rs.getString(5));
                sec.setText(rs.getString(6));
                add.setText(rs.getString(7));
                mob.setText(rs.getString(8));

                april.setText(rs.getString(9));
                may.setText(rs.getString(10));
                june.setText(rs.getString(11));
                july.setText(rs.getString(12));
               sch.setText(rs.getString(21));

            }

        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
        
         try{
            String url="jdbc:h2:~/scc";

            Connection con = DriverManager.getConnection(url,"scc","scc");
            Statement stmt=con.createStatement();
            String Query="SELECT april+may+june+july FROM STUDENT where adno = '"+l1.getSelectedValue()+"'";
            ResultSet rs=stmt.executeQuery(Query);

            while(rs.next())
            {
                tp.setText(rs.getString(1));
               
                

            }

        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
        
    }//GEN-LAST:event_l1ValueChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int result=l1.getNextMatch(t1.getText(), 0, Position.Bias.Forward);

        l1.setSelectedIndex(result);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new DBMS1().setVisible(false);
        new B1().setVisible(true);dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        if(l1.getSelectedValue()!=(null)){

            int reply= JOptionPane.showConfirmDialog(
                null,
                "Are you sure you want to Delete this Record from the DataBase ??",
                "*Warning* : Changes cannot be Reverted !",
                JOptionPane.YES_NO_OPTION);

            if(reply == JOptionPane.YES_OPTION)
            {
                try{
                    String url="jdbc:h2:~/scc";

                    Connection con = DriverManager.getConnection(url,"scc","scc");
                    Statement stmt=con.createStatement();
                    String Query="DELETE FROM STUDENT WHERE adno='"+l1.getSelectedValue()+"'";
                    stmt.execute(Query);
                    JOptionPane.showMessageDialog(null,"Selected Data Record(s) Deleted Successfully.");
                    cbox1.setSelectedItem("Change Class");

                    t1.setText(null);
                    adno.setText(null);
                    name.setText(null);
                    fname.setText(null);
                    dob.setText(null);
                    clas.setText(null);
                    sec.setText(null);
                    add.setText(null);
                    mob.setText(null);april.setText(null);
                    may.setText(null);
                    june.setText(null);
                    july.setText(null);
                    sch.setText(null);
                    tp.setText(null);
                    
                }
                catch(SQLException ex)
                {
                    JOptionPane.showMessageDialog(null, ex.toString());
                }
                FillList();
            }
            else
            if(reply == JOptionPane.NO_OPTION)
            {JOptionPane.showMessageDialog(null, "NO Record(s) have been deleted from the DataBase.");}

        }
        else {
            JOptionPane.showMessageDialog(null, "No Record(s) Selected.");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void clasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clasActionPerformed

    private void mayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mayActionPerformed

    private void cbox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox1ActionPerformed
String a=(String)cbox1.getSelectedItem();
        String b;
        switch(a)
        {

            case "11th":clas.setText("11th"); break;
            case "12th":clas.setText("12th"); break;
           

            default :
        }        // TODO add your handling code here:
    }//GEN-LAST:event_cbox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DBMS1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DBMS1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DBMS1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DBMS1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DBMS1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField add;
    private javax.swing.JTextField adno;
    private javax.swing.JTextField april;
    private javax.swing.JComboBox cbox1;
    private javax.swing.JTextField clas;
    private javax.swing.JTextField dob;
    private javax.swing.JTextField fname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField july;
    private javax.swing.JTextField june;
    private javax.swing.JList l1;
    private javax.swing.JTextField may;
    private javax.swing.JTextField mob;
    private javax.swing.JTextField name;
    private javax.swing.JTextField sch;
    private javax.swing.JTextField sec;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField tp;
    // End of variables declaration//GEN-END:variables
}
