import java.awt.Color;
import java.sql.*;
import static javafx.scene.control.ButtonBar.ButtonData.YES;
import javax.swing.*;
import javax.swing.text.Position;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SK
 */
public class feeStatus1 extends javax.swing.JFrame {
    final void FillList()
    {
    try{
        String url="jdbc:h2:~/scc";
        
     Connection con = DriverManager.getConnection(url,"scc","scc"); 
     Statement stmt=con.createStatement();
     String Query="SELECT * FROM STUDENT ORDER BY ADNO";
     ResultSet rs=stmt.executeQuery(Query);
     DefaultListModel DLM= new DefaultListModel();
     while(rs.next())
     {
     DLM.addElement(rs.getString(1));
     }
     l2.setModel(DLM);
    }
    catch(SQLException ex) 
       {
       JOptionPane.showMessageDialog(null, ex.toString());
       }
    }


    /**
     * Creates new form feeStatus1
     */
    public feeStatus1() {
        initComponents();
        FillList();
        setLocationRelativeTo(null);
        getContentPane().setBackground(new Color(255,255,153));
        
        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        l2 = new javax.swing.JList();
        mob = new javax.swing.JTextField();
        july = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        adno = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        sch = new javax.swing.JTextField();
        add = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        april = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        may = new javax.swing.JTextField();
        clas = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        june = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        sec = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        tp = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1320, 720));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Check & Update FEE Status");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 430, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("#Click on Admission No. to View Details.");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel30.setFont(new java.awt.Font("Microsoft JhengHei", 0, 15)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("DataBase : STUDENT");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 241, -1));

        jLabel8.setBackground(new java.awt.Color(204, 255, 204));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("# Enter Admission No. :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        t2.setBackground(new java.awt.Color(204, 255, 204));
        t2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 330, -1));

        jButton5.setBackground(new java.awt.Color(0, 0, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("SEARCH   DataBase");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 100, 330, 36));

        l2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Admission No.", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft JhengHei", 0, 14))); // NOI18N
        l2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        l2.setToolTipText("");
        l2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        l2.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                l2ValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(l2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 241, 380));

        mob.setEditable(false);
        mob.setBackground(new java.awt.Color(255, 255, 204));
        mob.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        getContentPane().add(mob, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, 507, -1));

        july.setBackground(new java.awt.Color(255, 255, 204));
        july.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(july, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 500, 120, -1));

        jLabel10.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Father's Name");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 131, -1));

        jLabel11.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("School Name");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, -1, -1));

        jLabel26.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        jLabel26.setText("+91");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, -1, -1));

        jLabel27.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        jLabel27.setText(" : ");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, -1, -1));

        jLabel28.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        jLabel28.setText(" : ");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, -1, -1));

        jLabel29.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        jLabel29.setText(" : ");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, -1, -1));

        adno.setEditable(false);
        adno.setBackground(new java.awt.Color(255, 255, 204));
        adno.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        getContentPane().add(adno, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, 537, -1));

        jLabel14.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Address");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 138, -1));

        fname.setEditable(false);
        fname.setBackground(new java.awt.Color(255, 255, 204));
        fname.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        getContentPane().add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, 537, -1));

        sch.setEditable(false);
        sch.setBackground(new java.awt.Color(255, 255, 204));
        sch.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        getContentPane().add(sch, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 220, 537, -1));

        add.setEditable(false);
        add.setBackground(new java.awt.Color(255, 255, 204));
        add.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 280, 537, -1));

        jLabel32.setFont(new java.awt.Font("Microsoft JhengHei", 0, 16)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel32.setText("*Total Fees Paid (Rs.) :");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 450, -1, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(51, 0, 204));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("# Fee Status #");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, -1, -1));

        april.setBackground(new java.awt.Color(255, 255, 204));
        april.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(april, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, 120, -1));

        jLabel33.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel33.setText("2nd Installment :");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, -1, -1));

        name.setEditable(false);
        name.setBackground(new java.awt.Color(255, 255, 204));
        name.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, 537, -1));

        may.setBackground(new java.awt.Color(255, 255, 204));
        may.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        may.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mayActionPerformed(evt);
            }
        });
        getContentPane().add(may, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, 120, -1));

        clas.setEditable(false);
        clas.setBackground(new java.awt.Color(255, 255, 204));
        clas.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        clas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clasActionPerformed(evt);
            }
        });
        getContentPane().add(clas, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, 538, -1));

        jLabel34.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel34.setText("3rd Installment :");
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 470, -1, -1));

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Admission No.*");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 131, -1));

        june.setBackground(new java.awt.Color(255, 255, 204));
        june.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(june, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, 120, -1));

        jLabel15.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Mobile No. ");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 138, -1));

        jLabel16.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        jLabel16.setText(" : ");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, -1, -1));

        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Name");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 131, -1));

        jLabel17.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        jLabel17.setText(" : ");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, -1, -1));

        jLabel35.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel35.setText("4th Installment :");
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 500, -1, -1));

        jLabel19.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        jLabel19.setText(" : ");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, -1, -1));

        jLabel20.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        jLabel20.setText(" : ");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, -1, -1));

        jLabel12.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Class");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 138, -1));

        jButton4.setBackground(new java.awt.Color(255, 0, 51));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("*Pay FEEs Now !");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, 160, 110));

        jButton3.setBackground(new java.awt.Color(204, 255, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 0, 153));
        jButton3.setText("Reset Fields");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 540, 160, 40));

        jLabel24.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel24.setText("(8-digits)");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 100, 115, -1));

        jLabel21.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("(50-characters)");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 160, 115, -1));

        jLabel22.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("(50-characters)");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 190, 115, -1));

        jLabel25.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel25.setText("(100-characters)");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 280, 115, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 135, 15));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home.jpg"))); // NOI18N
        jButton2.setText("     Return to HOME");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 640, -1, 48));

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei", 2, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("**Designed By, Saurav Kumar");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 660, 216, -1));

        jLabel46.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        jLabel46.setText(" : ");
        getContentPane().add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, -1, -1));

        sec.setEditable(false);
        sec.setBackground(new java.awt.Color(255, 255, 204));
        sec.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        getContentPane().add(sec, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, 537, -1));

        jLabel47.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel47.setText("Batch");
        getContentPane().add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 131, -1));

        tp.setEditable(false);
        tp.setBackground(new java.awt.Color(204, 255, 204));
        tp.setFont(new java.awt.Font("Microsoft JhengHei", 0, 15)); // NOI18N
        tp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(tp, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 450, 170, -1));

        jLabel36.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel36.setText("1st Installment  :");
        getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int result=l2.getNextMatch(t2.getText(), 0, Position.Bias.Forward);

        l2.setSelectedIndex(result);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void l2ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_l2ValueChanged

        try{
            String url="jdbc:h2:~/scc";

            Connection con = DriverManager.getConnection(url,"scc","scc");
            Statement stmt=con.createStatement();
            String Query="SELECT * FROM STUDENT where adno = '"+l2.getSelectedValue()+"'";
            ResultSet rs=stmt.executeQuery(Query);

            while(rs.next())
            {
                adno.setText(rs.getString(1));
                name.setText(rs.getString(2));
                fname.setText(rs.getString(3));
                
                clas.setText(rs.getString(5));
                sec.setText(rs.getString(6));
                add.setText(rs.getString(7));
                mob.setText(rs.getString(8));

                april.setText(rs.getString(9));
                may.setText(rs.getString(10));
                june.setText(rs.getString(11));
                july.setText(rs.getString(12));
                sch.setText(rs.getString(21));
                

            }

        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
        
        
        try{
            String url="jdbc:h2:~/scc";

            Connection con = DriverManager.getConnection(url,"scc","scc");
            Statement stmt=con.createStatement();
            String Query="SELECT april+may+june+july FROM STUDENT where adno = '"+l2.getSelectedValue()+"'";
            ResultSet rs=stmt.executeQuery(Query);

            while(rs.next())
            {
                tp.setText(rs.getString(1));
               
                

            }

        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
        
        
        
        
      
        
        
        
        
        
        
    }//GEN-LAST:event_l2ValueChanged

    private void mayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mayActionPerformed

    private void clasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clasActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        
        
        
      
        
        
        
        
        
        if(l2.getSelectedValue()==null)
{
JOptionPane.showMessageDialog(null,"No Records Selected.");
}
else{
         try
            {
                String url="jdbc:h2:~/scc";

                Connection con = DriverManager.getConnection(url,"scc","scc");
                Statement stmt=con.createStatement();
                String Query= "UPDATE STUDENT SET april='"+april.getText()+"',may='"+may.getText()+"',june='"+june.getText()+"',july='"+july.getText()+"'  WHERE adno = '"+l2.getSelectedValue()+"'";
                stmt.execute(Query);
                JOptionPane.showMessageDialog(null,"FEEs Paid & DataBase Updated Successfully.");
            }
            catch(SQLException ex)
            {
                JOptionPane.showMessageDialog(null, ex.toString());
            }
        
         
          try{
            String url="jdbc:h2:~/scc";

            Connection con = DriverManager.getConnection(url,"scc","scc");
            Statement stmt=con.createStatement();
            String Query="SELECT april+may+june+july FROM STUDENT where adno = '"+l2.getSelectedValue()+"'";
            ResultSet rs=stmt.executeQuery(Query);

            while(rs.next())
            {
                tp.setText(rs.getString(1));
               
                

            }

        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
}
       

                   
              
          

                
                
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        
        
        
        
        
        
        
        
        
       l2.setSelectedValue(null, false);
        
        t2.setText("");
        adno.setText(null);
        name.setText(null);
        fname.setText(null);
        sch.setText(null);
        clas.setText(null);
        sec.setText(null);
        add.setText(null);
        mob.setText(null);

        april.setText(null);
        may.setText(null);
        june.setText(null);
        july.setText(null);tp.setText(null);
         FillList();
        

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new feeStatus1().setVisible(false);
        new B1().setVisible(true); dispose();       // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(feeStatus1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(feeStatus1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(feeStatus1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(feeStatus1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new feeStatus1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField add;
    private javax.swing.JTextField adno;
    private javax.swing.JTextField april;
    private javax.swing.JTextField clas;
    private javax.swing.JTextField fname;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField july;
    private javax.swing.JTextField june;
    private javax.swing.JList l2;
    private javax.swing.JTextField may;
    private javax.swing.JTextField mob;
    private javax.swing.JTextField name;
    private javax.swing.JTextField sch;
    private javax.swing.JTextField sec;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField tp;
    // End of variables declaration//GEN-END:variables
}
