
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.awt.Color;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SK
 */
public class PA extends javax.swing.JFrame {
  public void bar()
  {
  t1.setFocusable(true);
  t1.enableInputMethods(true);
  
 
                try{
                    
                    String url="jdbc:h2:~/scc";
                    Connection con = DriverManager.getConnection(url,"scc","scc");
                    Statement stmt=con.createStatement();
                    String Query="SELECT * FROM key where num=1";
                    ResultSet rs=stmt.executeQuery(Query);
                    
                    
                    Statement smt1=con.createStatement();
                    String Quer1="SELECT year,month,date FROM key where num=1";
                    ResultSet rs1=smt1.executeQuery(Quer1);
                    
                     Statement smt2=con.createStatement();
                    String Quer2="SELECT year(curdate()),month(curdate()),day(curdate())";
                    ResultSet rs2=smt2.executeQuery(Quer2);

                    
                    
                    
                     while(rs.next()&& rs1.next()&& rs2.next())
            {
                int ye=rs1.getInt(1),
                        me=rs1.getInt(2),
                        de=rs1.getInt(3);
                String e1;
                
                            
   if(((de==1)||(de==2)||(de==3)||(de==4)||(de==5)||(de==6)||(de==7)||(de==8)||(de==9))&&((me==1)||(me==2)||(me==3)||(me==4)||(me==5)||(me==6)||(me==7)||(me==8)||(me==9)))
    e1=ye+"-0"+me+"-0"+de;
    else
     if((de==1)||(de==2)||(de==3)||(de==4)||(de==5)||(de==6)||(de==7)||(de==8)||(de==9))
       e1=ye+"-"+me+"-0"+de;
         else
          if((me==1)||(me==2)||(me==3)||(me==4)||(me==5)||(me==6)||(me==7)||(me==8)||(me==9))
               e1=ye+"-0"+me+"-"+de;
               else
               e1=ye+"-"+me+"-"+de; 
                
                
                
               
 int y=(int)rs2.getInt(1),
                        m=(int)rs2.getInt(2),
                        d=(int)rs2.getInt(3);
              
               
                
                   
                    
               
            
             
               
               
                
                
                
                
                
                
                
                
                
               String k=(rs.getString(1));
               
 
if((y<ye)||(y==ye && m<me)||(y==ye && m==me && d<de)||(ye==0 && me==0 && de==0))
{
               
               if(k.equals("FHR43-4HFXI-80HFG-4DG41-74HD1"))
{
   
 new PA().setVisible(false);
 new A1().setVisible(true);
               
        
        
}       
  else
{
new PA().setVisible(true);
}
               
}
else
    if((y==ye && m==me && d==de)||(y==ye && m==me && d>de)||(y==ye && m>me)||(y>ye))
    {
    JOptionPane.showMessageDialog(null,">> Your *Licence* has been ~EXPIRED~ on "+e1+". For Help Contact at 'saurav001books@rediffmail.com' <<");
    }
               
            }

                }
                catch(SQLException ex)
                {
                    JOptionPane.showMessageDialog(null, ex.toString());
                }
dispose();

  }

    /**
     * Creates new form PA
     */
    public PA() {
        initComponents();
        setLocationRelativeTo(null);
        getContentPane().setBackground(new Color(150,255,255));
        
        bar.setVisible(false);
        bar.setVisible(true);
                    bar.setIndeterminate(true);
        
        
        String k="FHR43-4HFXI-80HFG-4DG41-74HD1";
String g=(String)t1.getText();
        if(g.equals("FHR43-4HFXI-80HFG-4DG41-74HD1"))
        {
             t1.setForeground(Color.GREEN);
        }
            else
        {
          t1.setForeground(Color.BLUE);
        }
      
        
        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        bar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 550));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 0, 63)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Product  Activation*");

        t1.setFont(new java.awt.Font("Microsoft JhengHei", 0, 36)); // NOI18N
        t1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("*For example :  XXXXX-XXXXX-XXXXX-XXXXX-XXXXX");

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei", 2, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("**Designed By, Saurav Kumar");

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei", 0, 30)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Enter the Licence or Product Activation Key to Activate Application :");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Q.jpg"))); // NOI18N
        jButton2.setToolTipText("");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setPreferredSize(new java.awt.Dimension(1155, 600));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 204, 51));
        jButton3.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Activate Now !");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 0, 51));
        jButton4.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/feature-checkstatus - Copy.png"))); // NOI18N
        jButton4.setText(" Exit");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/information_round_sign_4231.jpg"))); // NOI18N
        jLabel4.setMinimumSize(new java.awt.Dimension(294, 256));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("CHECK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 992, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 867, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(242, 242, 242))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1)
                                .addGap(114, 114, 114)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1)))
                .addGap(51, 51, 51)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(t1)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap())
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JOptionPane.showMessageDialog(null,"To ACTIVATE Application, enter the *Product Activation KEY* provided at the time of purchasing the app. If you don't have one, then, Buy the *Licence Key* OR contact developer at 'saurav001books@rediffmail.com' for more details.");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
String z=t1.getText();

 try{
                    String url="jdbc:h2:~/scc";

                    Connection con = DriverManager.getConnection(url,"scc","scc");
                    Statement stmt=con.createStatement();
                    String Query="SELECT * FROM key where num=1";
                    ResultSet rs=stmt.executeQuery(Query);
                    
                     while(rs.next())
            {
               String k=(rs.getString(1));
               if(z.equals("FHR43-4HFXI-80HFG-4DG41-74HD1")|| z.equals(k))
{
   try{
                    String urll="jdbc:h2:~/scc";

                    Connection conn = DriverManager.getConnection(urll,"scc","scc");
                    Statement smt=conn.createStatement();
                    String Query1="UPDATE key SET key=('"+z+"') where num=1";
                    smt.execute(Query1);
                    
                    Statement smtt=conn.createStatement();
                    String Query2="UPDATE key SET actdate=curdate() where num=1";
                    smtt.execute(Query2);
                    
                    Statement smttt=conn.createStatement();
                    String Query3="UPDATE key SET year=year(actdate)+1 where num=1";
                    smttt.execute(Query3);
                    
                    Statement stt=conn.createStatement();
                    String Query4="UPDATE key SET month=month(actdate) where num=1";
                    stt.execute(Query4);
                    
                    Statement sm=conn.createStatement();
                    String Query5="UPDATE key SET date=day(actdate) where num=1";
                    sm.execute(Query5);
                    
                    t1.setForeground(Color.GREEN);
                    bar.setVisible(true);
                    bar.setIndeterminate(true);
 JOptionPane.showMessageDialog(null,"*Application Activated Successfully* !!");
 
 
 
 new PA().setVisible(false);
 new A1().setVisible(true);dispose();
                }
                catch(SQLException ex)
                {
                    JOptionPane.showMessageDialog(null, ex.toString());
                }
        
        
}       
  else
{
    t1.setForeground(Color.RED);
    bar.setVisible(true);
JOptionPane.showMessageDialog(null,"*INCORRECT Activation Key Entered !!*");
t1.setForeground(Color.BLUE);
t1.setText("");


}
            }

                }
                catch(SQLException ex)
                {
                    JOptionPane.showMessageDialog(null, ex.toString());
                }












        
        
        
        
        
        
        
        
        
        
        



// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
System.exit(WIDTH);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed

// TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 String k="FHR43-4HFXI-80HFG-4DG41-74HD1";
String g=(String)t1.getText();
        if(g.equals("FHR43-4HFXI-80HFG-4DG41-74HD1"))
        {
            bar.setVisible(true);
            bar.setIndeterminate(true);
            t1.setForeground(Color.GREEN);
        }
            else
        {
          t1.setForeground(Color.RED);
          bar.setVisible(true);
        }
              // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
        PA ob=new PA();
        ob.bar();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar bar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables
}
